apiVersion: v1
kind: Service
metadata:
    name: hello-node
    labels:
        name: hello-node
        app: demo
spec:
    selector:
        name: hello-node
    type: NodePort
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
