apiVersion: v1
kind: Pod
metadata:
    name: hello-node
    labels:
        name: hello-node
        app: demo
spec:
    containers:
      - name: hello-node
        image: hello-node:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
